basePath: /v1
host: beta.sonr.io
info:
  contact:
    email: help@sonr.io
    name: Sonr Team
    url: http://www.sonr.io/help
  description: This is a Gateway to the Sonr Blockchain Network.
  license:
    name: GNU Affero General Public License v3.0
    url: https://www.gnu.org/licenses/agpl-3.0.html
  termsOfService: http://swagger.io/terms/
  title: Sonr API
  version: "1.0"
paths: {}
swagger: "2.0"
